
include:
  - template: Code-Quality.gitlab-ci.yml

include:
  - template: Dependency-Scanning.gitlab-ci.yml

include:
  - template: Security/License-Scanning.gitlab-ci.yml

include:
  - template: Security/SAST.gitlab-ci.yml
  
include:
  - template: Secret-Detection.gitlab-ci.yml
